### ISSUE TITLE
Issue with Monk's TokenBar and Compact Roll Card DnD5e

### ISSUE THREAD

**Issue by fel-pt** [ElfFriend-DnD/foundryvtt-compact-roll-card-5e#2]
There's a compatibility issue between Monk's TokenBar and Compact Roll Card DnD5e. When clicking on the roll result to check what came up on the dice, the window showing the dice result will almost fill the entire screen.

Here are some screenshots showing what happens.

1. Before clicking on the result.
![1](https://user-images.githubusercontent.com/79886727/153020845-9e536f8a-f0d2-456d-a7dc-8e289764488b.jpg)

2. The intended behavior (only Monk's TokenBar active)
![2](https://user-images.githubusercontent.com/79886727/153020962-0e898c5e-04c5-42b7-a50d-d7747110c736.jpg)

3. The issue when both modules are active.
![3](https://user-images.githubusercontent.com/79886727/153021035-9788eecb-5c64-42cb-a2f7-4d2f34bffb0e.jpg)

I'm also posting this on [Monk's Tokenbar's issue list](https://github.com/ironmonk88/monks-tokenbar/issues/205).

**Comment by akrigline** [comment]
This isn't even a fully released module so there's not really an expectation of compatibility on my part, but good to know!

**Comment by fel-pt** [comment]
> This isn't even a fully released module so there's not really an expectation of compatibility on my part, but good to know!

Oh, sorry! I saw it mentioned on Reddit and I assumed it'd be worth it to warn you even before the full release.

Great job, by the way. It really makes the chat bar look a lot better :)
